<a href="https://colab.research.google.com/github/El-Gabi/CV/blob/main/amazon_coding_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Amazon Coding Challenge using Python Programming Language(Phase 1)

In my response to this challenge, from my knowledge about Data Structure and algorithms, there are different algorithms to solve this problem. But I chose to use the A Star Pathfinding Algorithm to solve this problem, because it is proven from different sources and online forums to have more effect than other algorithms.

In [1]:
#Firstly I  generate the 10 by 10 matrix with all possible paths
import numpy as np
A = np.ones((10,10))
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [2]:
# I assign the obstacle on the array by assigning the value zero to the location
A[9,7] = 0
A[8,7] = 0
A[6,7] = 0
A[6,8] = 0

In [3]:
#From the output, the obstacle location does not correlate with the visuals given in the Coding Challenge
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.]])

In [4]:
#I then transpose it to get the exact replica of the pictorial sample given but still couldn't but then I followed the positions of the obstacle stated in the challenge

#(9,7), (8,7), (6,7) and (6,8) are assigned zeros as the obstacles and 1 is the walking path
A = A.transpose()

In [5]:
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
#I installed the dependencies to enable use the algorithms for this task

In [6]:
pip install pathfinding

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
# First we import the dependencies in Python
from pathfinding.core.grid import Grid      # This is used to form the Grid positions
from pathfinding.core.diagonal_movement import DiagonalMovement   # This enables the algorithm to move diagonally in finding the shortestes path to the destination. 

In [8]:
# I create the grid of the matrix by calling the function

grid = Grid(matrix = A)

In [9]:
#Identify the start and finish node from the task
begin = grid.node(0,0)
delivery_point = grid.node(9,9)


In [10]:
#Create a pathfinder

from pathfinding.finder.a_star import AStarFinder  #The AStar Algorithm Module

finder = AStarFinder(diagonal_movement = DiagonalMovement.always)

# Now find the route

route,steps = finder.find_path(begin, delivery_point, grid)

In [11]:
print(route) # The path the algorithm took from start to finish

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]


In [12]:
print(steps) # The number of steps taken

10


Phase 2

In [13]:
# I get the shape of the array so as to fit the random numbers that will be generated into the shape
N = 10
M = 10

# How many entries to replace
REPLACE_COUNT = 20

# What to replace with
REPLACE_WITH = 0


# Get the data array.

print('Original: ')
print(A)

Original: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [14]:
#Here I randomly replace 20 numbers aside the starting and ending point

A.flat[np.random.choice(N * M, REPLACE_COUNT, replace=False)] = REPLACE_WITH
print('After replacement: ')
print(A)

After replacement: 
[[1. 1. 0. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 0. 1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 0. 1. 1. 0.]
 [1. 1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1. 1. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 1. 1. 1. 1.]]


In [15]:
# Get the grid
grid2 = Grid(matrix = A)

In [16]:
#Identify the start and finish node from the task
begin2 = grid2.node(0,0)
delivery_point2 = grid2.node(9,9)


In [17]:
# Now find the route

route2,steps2 = finder.find_path(begin2, delivery_point2, grid2)

In [18]:
print("The route from start to delivery is: ", route2)

The route from start to delivery is:  [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 5), (7, 6), (7, 7), (8, 8), (9, 9)]


In [19]:
print("The number of steps from start to delivery is: ", steps2)

The number of steps from start to delivery is:  19


In [ ]:
# I gave this my best shot though not much commercial awareness.

In [20]:
print ("Hello")

Hello


In [47]:
import numpy as np

b = [[1, 1, 1, 1, 1, 1],
     [1, 0, 1, 0, 1, 1],
     [1, 1, 0, 0, 1, 1]]

import random

a=[]
n=int(input("Enter number of elements:"))

for j in range(n):
       a.append(random.randint(0,1))

print('Randomised list is: ',a)

Enter number of elements:7
Randomised list is:  [0, 0, 0, 0, 1, 0, 0]
